### ISSUE TITLE
US Bug in covid 19 confirmed by country total tvsb

### ISSUE THREAD

**Issue by CarlosLannister** [siscale/covid-19-elk#2]
Hello, 

Right now there is a bug in the Kibana visualization covid 19 confirmed by country total tvsb. The US is not correctly represented. 

![image](https://user-images.githubusercontent.com/2520132/77831039-fa4be900-712c-11ea-9f0c-c99ce4be1c8c.png)

In your [post](https://www.siscale.com/importing-covid-19-data-into-elasticsearch/)  your dashboard seems to represent correctly the results.

**Comment by mateibm** [comment]
Hello, the pipeline has been updated since the blog was posted. Are you using the latest version of the pipeline from [here?](https://github.com/siscale/covid-19-elk/blob/master/logstash-github-covid-19-daily-reports-template.conf)

I recommend deleting the index and updating/restarting the pipeline. If you're already using the new pipeline, don't forget to delete the cache (located by default at `/etc/logstash/covid-19-hashes.json`)

**Comment by iamhowardtheduck** [comment]
Good day!  I've been using a fresh install and the latest pipeline, but I too have noticed the US & South Korean totals are not summing properly.

**Comment by mateibm** [comment]
Thank you for your feedback! We have reviewed the data set and found some inconsistencies in the naming convention for South Korea, and a few other cases that slipped by. The updated pipeline will refer to South Korea as 'Korea, South', to be consistent with the naming convention from the latest daily report (as of now, the daily report from 30.03.2020)

Please delete the current index and the cache (`/etc/logstash/covid-19-hashes.json`) before applying the new pipeline.

**Comment by iamhowardtheduck** [comment]
Thank you!
